const Paths=[
    {
        name: 'aliade',
        state : "Move",
        path : [
            { // Abajo
                x: 3816.00,
                y: 3682,
                offsetX: 30,
                offsetY: 4.5,
                dirX: 0,
                dirY: 1,
                index : 1
            },
            { // Derecha
                x: 4354,
                y: 3667,
                offsetX: 4,
                offsetY: 20,
                dirX: 1,
                dirY: 0,
                index : 2
            },
            { // Arriba
                x: 4354,
                y: 3435,
                offsetX: 20,
                offsetY: 5,
                dirX: 0,
                dirY: -1,
                index : 3
            },
            { // Derecha
                x: 5744,
                y: 3435,
                offsetX: 5,
                offsetY: 20,
                dirX: 1,
                dirY: 0,
                index : 4
            },
            { // Arriba
                x: 5744,
                y: 2904,
                offsetX: 15,
                offsetY: 5,
                dirX: 0,
                dirY: -1,
                index : 5
            },
            {// Izquierda
                x: 4654,
                y: 2904,
                offsetX: 4,
                offsetY: 15,
                dirX: -1,
                dirY: 0,
                index : 6
            },

            {// Arriba
                x: 4654,
                y: 2904,
                offsetX: 4,
                offsetY: 15,
                dirX: 0,
                dirY: -1,
                index : 7
            },
            {// Arriba
                x: 4654,
                y: 2740,
                offsetX: 14,
                offsetY: 4,
                dirX: 0,
                dirY: -1,
                index : 8
            },
            { // Izquierda
                x: 4000,
                y: 2740,
                offsetX: 4,
                offsetY: 15,
                dirX: -1,
                dirY: 0,
                index : 9
            },
            { // Abajo
                x: 4000,
                y: 2842,
                offsetX: 15,
                offsetY: 5,
                dirX: 0,
                dirY: 1,
                index : 10
            },
            {// Izquierda
                x: 3876,
                y: 2842,
                offsetX: 3,
                offsetY: 15,
                dirX: -1,
                dirY: 0,
                index : 11
            },
            {// Abajo
                x: 3876,
                y: 2990,
                offsetX: 16,
                offsetY: 5,
                dirX: 0,
                dirY: 1,
                index : 12
            },
            {// Izquierda
                x: 3821,
                y: 2990,
                offsetX: 5,
                offsetY: 15,
                dirX: -1,
                dirY: 0,
                index : 0
            }

        ]
    },
    {
        name: 'auronplay',
        state : "Move",
        path : [
            {// Derecha
                x: 2070.00,
                y: 1678,
                offsetX: 4,
                offsetY: 20,
                dirX: 1,
                dirY: 0,
                index : 1
            },
            {// Izquierda
                x: 1440.00,
                y: 1678,
                offsetX: 4,
                offsetY: 20,
                dirX: -1,
                dirY: 0,
                index : 0
            }
        ]
    },
    {
        name: 'lacoletas',
        state : "Move",
        path : [
            {// Izquierda
                x: 1155.00,
                y: 2400,
                offsetX: 4,
                offsetY: 50,
                dirX: -1,
                dirY: 0,
                index : 1
            },
            {// Abajo
                x: 1155.00,
                y: 2840,
                offsetX: 50,
                offsetY: 4,
                dirX: 0,
                dirY: 1,
                index : 2
            },
            {// Derecha
                x: 2655.00,
                y: 2825,
                offsetX: 3,
                offsetY: 50,
                dirX: 1,
                dirY: 0,
                index : 3
            },
            {// Arriba
                x: 2655.00,
                y: 2720,
                offsetX: 50,
                offsetY: 3,
                dirX: 0,
                dirY: -1,
                index : 4
            },
            {// Derecha
                x: 3650.00,
                y: 2720,
                offsetX: 3,
                offsetY: 50,
                dirX: 1,
                dirY: 0,
                index : 5
            },
            {// Abajo
                x: 3650.00,
                y: 2800,
                offsetX: 50,
                offsetY: 3,
                dirX: 0,
                dirY: 1,
                index : 6,
            },
            {// Derecha
                x: 3850.00,
                y: 2800,
                offsetX: 3,
                offsetY: 50,
                dirX: 1,
                dirY: 0,
                index : 7,
            },
            {// Arriba
                x: 3850.00,
                y: 2650,
                offsetX: 50,
                offsetY: 3,
                dirX: 0,
                dirY: -1,
                index : 8,
            },
            {// Derecha
                x: 3950.00,
                y: 2650,
                offsetX: 3,
                offsetY: 50,
                dirX: 1,
                dirY: 0,
                index : 9,
            },
            {// Arriba
                x: 3950.00,
                y: 2125,
                offsetX: 70,
                offsetY: 6,
                dirX: 0,
                dirY: -1,
                index : 10,
            },
            {// Izquierda
                x: 3110.00,
                y: 2125,
                offsetX: 6,
                offsetY: 50,
                dirX: -1,
                dirY: 0,
                index : 11,
            },
            {// Abajo
                x: 3110.00,
                y: 2255,
                offsetX: 50,
                offsetY: 6,
                dirX: 0,
                dirY: 1,
                index : 12,
            },
            {// Izquierda
                x: 2532.00,
                y: 2255,
                offsetX: 5,
                offsetY: 50,
                dirX: -1,
                dirY: 0,
                index : 13,
            },
            {// Arriba
                x: 2532.00,
                y: 1980,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: -1,
                index : 14,
            },
            {// Derecha
                x: 2832.00,
                y: 1980,
                offsetX: 5,
                offsetY: 50,
                dirX: 1,
                dirY: 0,
                index : 15,
            },
            {// Arriba
                x: 2832.00,
                y: 1740,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: -1,
                index : 16,
            },
            {// Izquierda
                x: 2533.00,
                y: 1740,
                offsetX: 5,
                offsetY: 50,
                dirX: -1,
                dirY: 0,
                index : 17,
            },
            {// Arriba
                x: 2533.00,
                y: 1546,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: -1,
                index : 18,
            },
            {// Izquierda
                x: 2285.00,
                y: 1546,
                offsetX: 5,
                offsetY: 50,
                dirX: -1,
                dirY: 0,
                index : 19,
            },
            {// Abajo
                x: 2285.00,
                y: 2128,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: 1,
                index : 20,
            },
            {// Izquierda
                x: 1507.00,
                y: 2128,
                offsetX: 5,
                offsetY: 50,
                dirX: -1,
                dirY: 0,
                index : 21,
            },
            {// Abajo
                x: 1507.00,
                y: 2400,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: 1,
                index : 0,
            },
            
        ]
    },
    {
        name: 'messi',
        state : "NoMove",
        dirX : 0,
        dirY : 1
    },
    {
        name: 'NinoPeroCascos',
        state : "Move",
        path :[
            {// Abajo
                x: 905.00,
                y: 2950,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: 1,
                index : 1,
            },
            {// Arriba
                x: 905.00,
                y: 950,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: -1,
                index : 0,
            }
        ]
    },
    {
        name: 'NinoPeroChef',
        state : "Move",
        path :[
            {// Derecha
                x: 3590.00,
                y: 2212,
                offsetX: 5,
                offsetY: 50,
                dirX: 1,
                dirY: 0,
                index : 1,
            },
            {// Arriba
                x: 3590.00,
                y: 2050,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: -1,
                index : 2,
            },
            {// Izquierda
                x: 3400.00,
                y: 2050,
                offsetX: 5,
                offsetY: 50,
                dirX: -1,
                dirY: 0,
                index : 3,
            },
            {// Arriba
                x: 3400.00,
                y: 1890,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: -1,
                index : 4,
            },
            {// Derecha
                x: 3590.00,
                y: 1890,
                offsetX: 5,
                offsetY: 50,
                dirX: 1,
                dirY: 0,
                index : 5,
            },
            {// Arriba
                x: 3590.00,
                y: 1730,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: -1,
                index : 6,
            },
            {// Izquierda
                x: 3400.00,
                y: 1730,
                offsetX: 5,
                offsetY: 50,
                dirX: -1,
                dirY: 0,
                index : 7,
            },
            {// Arriba
                x: 3400.00,
                y: 1560,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: -1,
                index : 8,
            },
            {// Derecha
                x: 3590.00,
                y: 1560,
                offsetX: 5,
                offsetY: 50,
                dirX: 1,
                dirY: 0,
                index : 9,
            },
            {// Arriba
                x: 3590.00,
                y: 1410,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: -1,
                index : 10,
            },
            {// Izquierda
                x: 3400.00,
                y: 1410,
                offsetX: 5,
                offsetY: 50,
                dirX: -1,
                dirY: 0,
                index : 11,
            },
            {// Arriba
                x: 3400.00,
                y: 1035,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: -1,
                index : 12,
            },
            {// Derecha
                x: 3590.00,
                y: 1035,
                offsetX: 50,
                offsetY: 5,
                dirX: 1,
                dirY: 0,
                index : 13,
            },
            {// Abajo
                x: 3590.00,
                y: 1320,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: 1,
                index : 14,
            },
            {// Izquierda
                x: 3400.00,
                y: 1320,
                offsetX: 5,
                offsetY: 50,
                dirX: -1,
                dirY: 0,
                index : 15,
            },
            {// Abajo
                x: 3400.00,
                y: 1410,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: 1,
                index : 16,
            },
            {// Derecha
                x: 3590.00,
                y: 1410,
                offsetX: 5,
                offsetY: 50,
                dirX: 1,
                dirY: 0,
                index : 17,
            },
            {// Abajo
                x: 3590.00,
                y: 1560,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: 1,
                index : 18,
            },
            {// Izquierda
                x: 3400.00,
                y: 1560,
                offsetX: 5,
                offsetY: 50,
                dirX: -1,
                dirY: 0,
                index : 19,
            },
            {// Abajo
                x: 3400.00,
                y: 1730,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: 1,
                index : 20,
            },
            {// Derecha
                x: 3590.00,
                y: 1730,
                offsetX: 5,
                offsetY: 50,
                dirX: 1,
                dirY: 0,
                index : 21,
            },
            {// Abajo
                x: 3590.00,
                y: 1890,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: 1,
                index : 22,
            },
            {// Izquierda
                x: 3400.00,
                y: 1890,
                offsetX: 5,
                offsetY: 50,
                dirX: -1,
                dirY: 0,
                index : 23,
            },
            {// Abajo
                x: 3400.00,
                y: 2050,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: 1,
                index : 24,
            },
            {// Derecha
                x: 3590.00,
                y: 2050,
                offsetX: 5,
                offsetY: 50,
                dirX: 1,
                dirY: 0,
                index : 25,
            }, 
            {// Abajo
                x: 3590.00,
                y: 2212,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: 1,
                index : 26,
            },
            {// Izquierda
                x: 3400.00,
                y: 2212,
                offsetX: 5,
                offsetY: 50,
                dirX: -1,
                dirY: 0,
                index : 0,
            },
        ]
    },
    {
        name: 'NinoPeroChef2',
        state : "NoMove",
        dirX : 0,
        dirY : 1
    },
    {
        name: 'niñoCabezon',
        state : "NoMove",
        dirX : 0,
        dirY : -1
    },
    {
        name: 'señora1',
        state : "NoMove",
        dirX : 1,
        dirY : 0
    },

    {
        name: 'señorPendiente',
        state : "Move",
        path :[
            {// Derecha
                x: 6550.00,
                y: 1630,
                offsetX: 5,
                offsetY: 50,
                dirX: 1,
                dirY: 0,
                index : 1,
            },
            {// Abajo
                x: 6550.00,
                y: 1820,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: 1,
                index : 2,
            },
            {// Izquierda
                x: 5570.00,
                y: 1820,
                offsetX: 5,
                offsetY: 50,
                dirX: -1,
                dirY: 0,
                index : 3,
            },
            {// Arriba
                x: 5570.00,
                y: 1630,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: -1,
                index : 0,
            }
        ]
    },
    {
        name: 'UnOtaku_1',
        state : "Move",
        path :[
            {// Abajo
                x: 7240.00,
                y: 1570,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: 1,
                index : 1,
            },
            {// Arriba
                x: 7240.00,
                y: 1030,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: -1,
                index : 0,
            },
        ]
    },
    {
        name: 'rubiacoletas',
        state : "Move",
        path :[
            {// Derecha
                x: 5750.00,
                y: 922,
                offsetX: 5,
                offsetY: 50,
                dirX: 1,
                dirY: 0,
                index : 1,
            },
            {// Izquierda
                x: 4900.00,
                y: 922,
                offsetX: 5,
                offsetY: 50,
                dirX: -1,
                dirY: 0,
                index : 0,
            },
        ]
    },
    {
        name: 'niñoflequillo',
        state : "Move",
        path :[
            {// Derecha
                x: 1900.00,
                y: 5584,
                offsetX: 5,
                offsetY: 50,
                dirX: 1,
                dirY: 0,
                index : 1,
            },
            {// Izquierda
                x: 1040.00,
                y: 5584,
                offsetX: 5,
                offsetY: 50,
                dirX: -1,
                dirY: 0,
                index : 0,
            },
        ]
    },
    {
        name: 'NinoPeroChef4',
        state : "Move",
        path :[
            {// Derecha
                x: 4330.00,
                y: 3670,
                offsetX: 5,
                offsetY: 50,
                dirX: 1,
                dirY: 0,
                index : 1,
            },
            {// Abajo
                x: 4330.00,
                y: 3834,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: 1,
                index : 2,
            },
            {// Izquierda
                x: 3150.00,
                y: 3834,
                offsetX: 5,
                offsetY: 50,
                dirX: -1,
                dirY: 0,
                index : 3,
            },
            {// Arriba
                x: 3150.00,
                y: 3670,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: -1,
                index : 0,
            },
        ]
    },
    {
        name: 'NinoPeroChef3',
        state : "Move",
        path :[
            {// Derecha
                x: 2226.00,
                y: 4380,
                offsetX: 5,
                offsetY: 50,
                dirX: 1,
                dirY: 0,
                index : 1,
            },
            {// Abajo
                x: 2226.00,
                y: 4910,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: 1,
                index : 2,
            },
            {// Derecha
                x: 2717.00,
                y: 4910,
                offsetX: 50,
                offsetY: 5,
                dirX: 1,
                dirY: 0,
                index : 3,
            },
            {// Arriba
                x: 2717.00,
                y: 4380,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: -1,
                index : 4,
            },
            {// Izquierda
                x: 2226.00,
                y: 4380,
                offsetX: 50,
                offsetY: 5,
                dirX: -1,
                dirY: 0,
                index : 1,
            },
        ]
    },
    {
        name: 'Oficinista',
        state : "Move",
        path :[
            {// Derecha
                x: 6760.00,
                y: 5574,
                offsetX: 5,
                offsetY: 50,
                dirX: 1,
                dirY: 0,
                index : 1,
            },
            {// Izquierda
                x: 5400.00,
                y: 5574,
                offsetX: 5,
                offsetY: 50,
                dirX: -1,
                dirY: 0,
                index : 0,
            },
        ]
    },
    {
        name: 'UnViejo_1',
        state : "Move",
        path :[
            { //Derecha
                x: 6428.00,
                y: 4030,
                offsetX: 5,
                offsetY: 50,
                dirX: 1,
                dirY: 0,
                index : 1,
            },
            { //Arriba
                x: 6428.00,
                y: 3558,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: -1,
                index : 2,
            },
            { //Derecha
                x: 7269.00,
                y: 3558,
                offsetX: 5,
                offsetY: 50,
                dirX: 1,
                dirY: 0,
                index : 3,
            },
            { //Abajo
                x: 7269.00,
                y: 4069,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: 1,
                index : 4,
            },
            { //Izquierda
                x: 7054.00,
                y: 4069,
                offsetX: 5,
                offsetY: 50,
                dirX: -1,
                dirY: 0,
                index : 5,
            },
            { //Abajo
                x: 7054.00,
                y: 4976,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: 1,
                index : 6,
            },
            { //Izquierda
                x: 6788.00,
                y: 4976,
                offsetX: 5,
                offsetY: 50,
                dirX: -1,
                dirY: 0,
                index : 7,
            },
            { //Arriba
                x: 6788.00,
                y: 4652,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: -1,
                index : 8,
            },
            { //Izquierda
                x: 6622.00,
                y: 4652,
                offsetX: 5,
                offsetY: 50,
                dirX: -1,
                dirY: 0,
                index : 9,
            },
            { //Arriba
                x: 6622.00,
                y: 4462,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: -1,
                index : 10,
            },
            { //Izquierda
                x: 6404.00,
                y: 4462,
                offsetX: 5,
                offsetY: 50,
                dirX: -1,
                dirY: 0,
                index : 11,
            },
            { //Arriba
                x: 6404.00,
                y: 4236,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: -1,
                index : 12,
            },
            { //Izquierda
                x: 5813.00,
                y: 4236,
                offsetX: 5,
                offsetY: 50,
                dirX: -1,
                dirY: 0,
                index : 13,
            },
            { //Arriba
                x: 5813.00,
                y: 4030,
                offsetX: 50,
                offsetY: 5,
                dirX: 0,
                dirY: -1,
                index : 0,
            },
        ]
    }
]
export default Paths